BEGIN TRANSACTION;
INSERT INTO "eSports_user_game" VALUES (1,'kogtrey',1,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (2,'VaccaFlacca',1,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (3,'MrBlueSky-729',1,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (4,'Klover',1,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (5,'Ulfrrr',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (6,'Rusk',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (7,'Shhy',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (8,'DiscoPotato99',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (9,'VegiKarp',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (10,'Jet Jaguar',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (11,'Maurtek',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (12,'Colz',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (13,'S3PH4R',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (14,'Archer66',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (15,'WishXII',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (16,'Dayze',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (17,'MoonMoonn',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (18,'Hefae',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (19,'Goes',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (20,'BearlyTwiggs',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (21,'Crashthehalls',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (22,'Cheeto11',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (23,'ClydeFrawwg',4,NULL,NULL);
INSERT INTO "eSports_user_game" VALUES (24,'Slop',4,NULL,NULL);
COMMIT;
