# Generated by Django 2.2.7 on 2020-02-13 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('platform', models.CharField(max_length=60)),
                ('launcher', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('stats', models.TextField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=60)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Rank',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('discord', models.CharField(blank=True, default=None, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eSports.User')),
                ('student_id', models.IntegerField()),
                ('gpa', models.PositiveSmallIntegerField()),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophmore'), ('JR', 'Junior'), ('SR', 'Senior'), ('UN', 'Unknown'), ('NA', 'Not Applicable')], max_length=2)),
                ('major', models.CharField(max_length=60)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, default=None, null=True)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eSports.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=60)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, default=None, null=True)),
                ('game_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eSports.Game')),
                ('rank_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eSports.Team_Rank')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eSports.Status')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eSports.Status'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eSports.User')),
                ('status', models.BooleanField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, default=None, null=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eSports.Role')),
            ],
        ),
        migrations.CreateModel(
            name='user_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_cap', models.BooleanField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, default=None, null=True)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eSports.Team')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eSports.Player')),
            ],
            options={
                'unique_together': {('user_id', 'team_id')},
            },
        ),
        migrations.CreateModel(
            name='user_game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eSports.Game')),
                ('stat_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eSports.Stats')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eSports.Player')),
            ],
            options={
                'unique_together': {('user_id', 'game_id')},
            },
        ),
    ]
