# Generated by Django 2.2.6 on 2019-11-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='pga',
            new_name='gpa',
        ),
        migrations.AlterField(
            model_name='player',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user_team',
            name='date_end',
            field=models.DateField(null=True),
        ),
    ]
