# Generated by Django 3.0.3 on 2020-02-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eSports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='description',
            field=models.TextField(default='stats'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='student_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stats',
            name='stats',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_game',
            name='stat_id',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eSports.Stats'),
        ),
        migrations.AlterField(
            model_name='user_game',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eSports.Player'),
        ),
    ]
