# Generated by Django 2.2.6 on 2019-11-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSports', '0002_auto_20191109_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='date_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user_team',
            name='date_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
