# Generated by Django 2.2.6 on 2019-11-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSports', '0005_auto_20191123_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='stat_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
