# Generated by Django 2.2.6 on 2019-11-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSports', '0006_auto_20191123_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='year',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophmore'), ('JR', 'Junior'), ('SR', 'Senior'), ('UN', 'Unknown'), ('NA', 'Not Applicable')], max_length=2),
        ),
    ]
