# Generated by Django 2.2.6 on 2019-11-24 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eSports', '0008_auto_20191124_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_game',
            name='stat_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eSports.Stats'),
        ),
    ]
